import classes from '../../styles/01_atoms/Loading.module.scss';

function Loading() {
  return (
    <>
      {/* [ldio] generated by https://loading.io/ */}
      <svg
        className={classes['loading-spinner']}
        xmlns='http://www.w3.org/2000/svg'
        style={{ margin: 'auto', display: 'block', shapeRendering: 'auto' }}
        width='200px'
        height='200px'
        viewBox='0 0 100 100'
        preserveAspectRatio='xMidYMid'
      >
        <circle
          cx='50'
          cy='50'
          fill='none'
          stroke='#faf9ef'
          strokeWidth='6'
          r='22'
          strokeDasharray='103.67255756846316 36.55751918948772'
        >
          <animateTransform
            attributeName='transform'
            type='rotate'
            repeatCount='indefinite'
            dur='1s'
            values='0 50 50;360 50 50'
            keyTimes='0;1'
          ></animateTransform>
        </circle>
      </svg>
    </>
  );
}
export default Loading;
